name: craftchat
# REPLACE VERSION NUMBER IN ANT BUILD FILE ON JENKINS #
version: CRAFTDEV
description: Craft Minecraft Chat Plugin
authors: [FireBall1725, roblabla]
website: http://www.craftminecraft.com

main: com.craftminecraft.craftchat.CraftChat
database: false

commands:
  msg:
    description: Sends message to a player on network.
    aliases: tell
    permission: cmc.chat.message
    usage: "Usage : /<command> [player] [message]"
permissions:
  cmc.chat.message:
    description: Sends message to a player on network.
    default: true
  cmc.chat.message.override:
    description: Allows to send message to anyone, even if not in friend list.
    default: op